build: off

environment:
  matrix:
    - job_name: Ubuntu
      appveyor_build_worker_image: Ubuntu2004
      APPVEYOR: True
      CI: True
    - job_name: MacOS
      appveyor_build_worker_image: macos
      APPVEYOR: True
      CI: True
    - job_name: Windows
      appveyor_build_worker_image: Visual Studio 2019
      CHERE_INVOKING: 1
      MSYSTEM: MINGW64
      RUBY_VERSION: 27

for:
  -
    matrix:
      only:
        - job_name: Ubuntu
    init:
      - sh: sudo apt-get install -y ncompress
    test_script:
      - sh: scripts/ci_test.sh
    after_test:
      - sh: bash <(curl -s "https://codecov.io/bash")

  -
    matrix:
      only:
        - job_name: MacOS
    init:
      # Using compress from latest ncompress.
      - sh: brew install ncompress
      - sh: ln -s /usr/local/opt/ncompress/bin/compress /usr/local/bin/compress
    test_script:
      - sh: sudo -E scripts/ci_test.sh
    after_test:
      - sh: bash <(curl -s "https://codecov.io/bash")

  -
    matrix:
      only:
        - job_name: Windows
    init:
      - cmd: set PATH=C:\Ruby%RUBY_VERSION%-x64\bin;%PATH%
      - cmd: C:\msys64\usr\bin\bash -cl "curl -L 'https://github.com/vapier/ncompress/releases/download/v4.2.4.6/compress-windows-x64.exe' -o 'C:\Windows\System32\compress.exe'"
    test_script:
      # Using special mingw prefix.
      - cmd: C:\msys64\usr\bin\bash -cl "./scripts/ci_test.sh /mingw64"
    after_test:
      - cmd: C:\msys64\usr\bin\bash -cl "bash <(curl -s 'https://codecov.io/bash')"
