build: off

environment:
  global:
    APPVEYOR: True
    CI: True

  matrix:
    - job_name: ubuntu (2.5)
      appveyor_build_worker_image: Ubuntu2004
      RUBY_VERSION: ruby-2.5
    - job_name: ubuntu (2.6)
      appveyor_build_worker_image: Ubuntu2004
      RUBY_VERSION: ruby-2.6
    - job_name: ubuntu (2.7)
      appveyor_build_worker_image: Ubuntu2004
      RUBY_VERSION: ruby-2.7
    # - job_name: ubuntu (3)
    #   appveyor_build_worker_image: Ubuntu2004
    #   RUBY_VERSION: ruby-3.0
    - job_name: macos (2.5)
      appveyor_build_worker_image: macos
      RUBY_VERSION: ruby-2.5
    - job_name: macos (2.6)
      appveyor_build_worker_image: macos
      RUBY_VERSION: ruby-2.6
    - job_name: macos (2.7)
      appveyor_build_worker_image: macos
      RUBY_VERSION: ruby-2.7
    # - job_name: macos (3)
    #   appveyor_build_worker_image: macos
    #   RUBY_VERSION: ruby-3.0
    - job_name: windows (2.5)
      appveyor_build_worker_image: Visual Studio 2019
      RUBY_VERSION: 25
    - job_name: windows (2.6)
      appveyor_build_worker_image: Visual Studio 2019
      RUBY_VERSION: 26
    - job_name: windows (2.7)
      appveyor_build_worker_image: Visual Studio 2019
      RUBY_VERSION: 27
    - job_name: windows (3)
      appveyor_build_worker_image: Visual Studio 2019
      RUBY_VERSION: 30
    - job_name: windows-mingw
      appveyor_build_worker_image: Visual Studio 2019
      MSYSTEM: MINGW64
    - job_name: windows-cygwin
      appveyor_build_worker_image: Visual Studio 2019
      CYGWIN_NOWINPATH: 1
      SHELLOPTS: igncr

for:
#   -
#     matrix:
#       only:
#         - job_name: ubuntu
#     init:
#       - sh: sudo apt-get update
#       - sh: sudo apt-get install -y ncompress
#     test_script:
#       - sh: scripts/ci_test.sh
#     after_test:
#       - sh: bash <(curl -s "https://codecov.io/bash")

#   -
#     matrix:
#       only:
#         - job_name: macos
#     init:
#       # Using compress from latest ncompress.
#       - sh: brew update
#       - sh: brew install ncompress
#       - sh: ln -s /usr/local/opt/ncompress/bin/compress /usr/local/bin/compress
#     test_script:
#       - sh: sudo -E scripts/ci_test.sh
#     after_test:
#       - sh: bash <(curl -s "https://codecov.io/bash")

#   -
#     matrix:
#       only:
#         - job_name: windows
#     init:
#       - cmd: set "PATH=C:\Ruby%RUBY_VERSION%-x64\bin;%PATH%"
#       - cmd: >-
#           C:\msys64\usr\bin\bash -cl '
#           curl -L "https://github.com/vapier/ncompress/releases/download/v5.0/compress-windows-x64.exe"
#           -o "C:\Windows\System32\compress.exe"
#           '
#     test_script:
#       # Using special mingw prefix.
#       - cmd: C:\msys64\usr\bin\bash -cl "./scripts/ci_test.sh /mingw64"
#     after_test:
#       - cmd: C:\msys64\usr\bin\bash -cl "bash <(curl -s 'https://codecov.io/bash')"

  -
    matrix:
      only:
        - job_name: windows-cygwin
    init:
      - cmd: >-
          C:\cygwin64\setup-x86_64.exe --quiet-mode --only-site
          --site "https://mirrors.kernel.org/sourceware/cygwin"
          --root "C:\cygwin64"
          --local-package-dir "C:\cygwin64\var\cache\setup"
          --packages "curl,cmake,make,gcc-g++,libgmp-devel,libtommath-devel,git,ruby"
      - cmd: >-
          C:\cygwin64\bin\bash -cl '
          curl -L "https://github.com/vapier/ncompress/releases/download/v5.0/compress-windows-x64.exe"
          -o "C:\Windows\System32\compress.exe"
          '
    test_script:
      - cmd: set "PATH="
      - cmd: C:\cygwin64\bin\bash -l "%cd%\scripts\ci_test.sh"
