build: off

environment:
  global:
    APPVEYOR: True
    CI: True

  matrix:
    - job_name: ubuntu (2.6)
      appveyor_build_worker_image: Ubuntu2004
      RUBY_VERSION: ruby-2.6
    - job_name: ubuntu (2.7)
      appveyor_build_worker_image: Ubuntu2004
      RUBY_VERSION: ruby-2.7
    - job_name: ubuntu (3.0)
      appveyor_build_worker_image: Ubuntu2004
      RUBY_VERSION: ruby-3.0
    - job_name: macos (2.6)
      appveyor_build_worker_image: macos
      RUBY_VERSION: ruby-2.6
    - job_name: macos (2.7)
      appveyor_build_worker_image: macos
      RUBY_VERSION: ruby-2.7
    - job_name: macos (3.0)
      appveyor_build_worker_image: macos
      RUBY_VERSION: ruby-3.0
    - job_name: windows-mingw
      appveyor_build_worker_image: Visual Studio 2022
      MSYSTEM: MINGW64

for:
  -
    matrix:
      only:
        - job_name: ubuntu (2.6)
        - job_name: ubuntu (2.7)
        - job_name: ubuntu (3.0)
    init:
      - sh: sudo apt-get install -y libgmp-dev libtommath-dev ncompress
    test_script:
      - sh: rvm use "$RUBY_VERSION"
      - sh: scripts/ci_test.sh

  -
    matrix:
      only:
        - job_name: macos (2.6)
        - job_name: macos (2.7)
        - job_name: macos (3.0)
    init:
      - sh: brew install gmp libtommath ncompress
      - sh: ln -s /usr/local/opt/ncompress/bin/compress /usr/local/bin/compress
    test_script:
      - sh: rvm use "$RUBY_VERSION"
      - sh: scripts/ci_test.sh

  -
    matrix:
      only:
        - job_name: windows-mingw
    init:
      - cmd: >-
          C:\msys64\usr\bin\bash -cl "
          pacman --sync --noconfirm --needed
          git
          make
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-curl
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gmp
          mingw-w64-x86_64-libtommath
          mingw-w64-x86_64-ruby
          "
      - cmd: >-
          curl -L "https://github.com/vapier/ncompress/releases/download/v5.0/compress-windows-x64.exe"
          -o "C:\msys64\usr\bin\compress.exe"
    test_script:
      - cmd: C:\msys64\usr\bin\bash -l "%cd%\scripts\ci_test.sh"
