build: off

environment:
  global:
    APPVEYOR: True
    CI: True

  matrix:
    - job_name: ubuntu (2.5)
      appveyor_build_worker_image: Ubuntu2004
      RUBY_VERSION: ruby-2.5
    - job_name: ubuntu (2.6)
      appveyor_build_worker_image: Ubuntu2004
      RUBY_VERSION: ruby-2.6
    - job_name: ubuntu (2.7)
      appveyor_build_worker_image: Ubuntu2004
      RUBY_VERSION: ruby-2.7
    # - job_name: ubuntu (3)
    #   appveyor_build_worker_image: Ubuntu2004
    #   RUBY_VERSION: ruby-3.0
    - job_name: macos (2.5)
      appveyor_build_worker_image: macos
      RUBY_VERSION: ruby-2.5
    - job_name: macos (2.6)
      appveyor_build_worker_image: macos
      RUBY_VERSION: ruby-2.6
    - job_name: macos (2.7)
      appveyor_build_worker_image: macos
      RUBY_VERSION: ruby-2.7
    # - job_name: macos (3)
    #   appveyor_build_worker_image: macos
    #   RUBY_VERSION: ruby-3.0
    - job_name: windows-mingw
      appveyor_build_worker_image: Visual Studio 2019
      MSYSTEM: MINGW64
    - job_name: windows-cygwin
      appveyor_build_worker_image: Visual Studio 2019
      CYGWIN_NOWINPATH: True
      SHELLOPTS: igncr

for:
  -
    matrix:
      only:
        - job_name: ubuntu (2.5)
        - job_name: ubuntu (2.6)
        - job_name: ubuntu (2.7)
        # - job_name: ubuntu (3)
    init:
      - sh: sudo apt-get install -y gcc llvm clang libgmp-dev libtommath-dev ncompress
    test_script:
      - sh: rvm use "$RUBY_VERSION"
      - sh: scripts/ci_test.sh

  -
    matrix:
      only:
        - job_name: macos (2.5)
        - job_name: macos (2.6)
        - job_name: macos (2.7)
        # - job_name: macos (3)
    init:
      - sh: brew install gcc llvm gmp libtommath ncompress
      - sh: ln -s /usr/local/opt/ncompress/bin/compress /usr/local/bin/compress
    test_script:
      - sh: rvm use "$RUBY_VERSION"
      - sh: scripts/ci_test.sh

  -
    matrix:
      only:
        - job_name: windows-mingw
    init:
      - cmd: >-
          C:\msys64\usr\bin\bash -cl "
          pacman --sync --noconfirm --needed
          make
          git
          mingw-w64-x86_64-curl
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-gmp
          mingw-w64-x86_64-libtommath
          mingw-w64-x86_64-ruby
          "
      - cmd: >-
          curl -L "https://github.com/vapier/ncompress/releases/download/v5.0/compress-windows-x64.exe"
          -o "C:\msys64\usr\bin\compress.exe"
    test_script:
      - cmd: C:\msys64\usr\bin\bash -l "%cd%\scripts\ci_test.sh"

  -
    matrix:
      only:
        - job_name: windows-cygwin
    init:
      - cmd: >-
          C:\cygwin64\setup-x86_64.exe --quiet-mode --only-site
          --site "https://mirrors.kernel.org/sourceware/cygwin"
          --root "C:\cygwin64"
          --local-package-dir "C:\cygwin64\var\cache\setup"
          --packages "curl,cmake,make,gcc-g++,libgmp-devel,libtommath-devel,git,ruby-devel"
      - cmd: >-
          curl -L "https://github.com/vapier/ncompress/releases/download/v5.0/compress-windows-x64.exe"
          -o "C:\cygwin64\bin\compress.exe"
    test_script:
      - cmd: C:\cygwin64\bin\bash -l "%cd%\scripts\ci_test.sh"
