language: ruby
rvm:
  - 2.6

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libgmp-dev
      - ncompress
  homebrew:
    packages:
      - gmp
      - ncompress

before_install:
  - gem install bundler

script:
  - scripts/ci_test.sh
