language: ruby
rvm:
  - 2.6

os:
  - linux
  - osx

dist: bionic
osx_image: xcode11.2

arch:
  - amd64
  - arm64

addons:
  apt:
    packages:
      - cmake
      - libgmp-dev
      - ncompress
  homebrew:
    packages:
      - gmp
      - ncompress
    update: true

before_install:
  - gem install bundler

script:
  - scripts/ci_test.sh

after_success:
  - bash <(curl -s "https://codecov.io/bash")
