language: ruby
rvm:
  - "2.6.3"

os:
  - linux
  - osx

dist: xenial
osx_image: xcode10.2

addons:
  apt:
    packages:
      - libgmp-dev
      - ncompress
  homebrew:
    packages:
      - gmp
      - ncompress

script:
  - scripts/test.sh
