name: test

on:
  - push

jobs:
  ubuntu:
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup dependencies
        run: sudo apt-get install -y ncompress

      - name: CI test
        run: sudo scripts/ci_test.sh

  macos:
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7

    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup dependencies
        # Using compress from latest ncompress.
        run: |
          brew install ncompress
          ln -s /usr/local/opt/ncompress/bin/compress /usr/local/bin/compress

      - name: CI test
        run: sudo scripts/ci_test.sh

  windows:
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7

    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup dependencies
        run: curl -L 'https://github.com/vapier/ncompress/releases/download/v4.2.4.6/compress-windows-x64.exe' -o 'C:\Windows\System32\compress.exe'

      - name: CI test
        # Using special mingw prefix.
        run: scripts/ci_test.sh /mingw64
        shell: bash
