name: test

on:
  - push

jobs:
  ubuntu:
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup dependencies
        run: sudo apt-get install -y libgmp-dev libtommath-dev ncompress
      - name: CI test
        run: scripts/ci_test.sh

  macos:
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup dependencies
        run: |
          brew install gmp libtommath ncompress
          ln -s /usr/local/opt/ncompress/bin/compress /usr/local/bin/compress
      - name: CI test
        run: scripts/ci_test.sh

  windows:
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup dependencies
        run: >-
            curl -L "https://github.com/vapier/ncompress/releases/download/v5.0/compress-windows-x64.exe"
            -o "C:\Windows\System32\compress.exe"
      - name: CI test
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          git clone "https://github.com/libtom/libtommath.git" --depth 1 && cd "libtommath"
          nmake -f "makefile.msvc" install && cd ..
          set "INCLUDE=C:\devel\include;%INCLUDE%" && set "LIB=C:\devel\lib;%LIB%" && set "PATH=C:\devel\bin;%PATH%"
          call "C:\Program Files\Git\bin\bash.exe" -l "%cd%\scripts\ci_test.sh"

  windows-mingw:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 "{0}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            make
            git
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gmp
            mingw-w64-x86_64-libtommath
            mingw-w64-x86_64-ruby
      - name: Setup dependencies
        run: >-
            curl -L "https://github.com/vapier/ncompress/releases/download/v5.0/compress-windows-x64.exe"
            -o "/usr/bin/compress.exe"
      - name: CI test
        run: scripts/ci_test.sh
        env:
          MSYSTEM: MINGW64

  windows-cygwin:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          install-dir: C:\cygwin64
          packages: curl cmake make gcc-g++ libgmp-devel libtommath-devel git ruby-devel
      - name: Setup dependencies
        run: >-
            curl -L "https://github.com/vapier/ncompress/releases/download/v5.0/compress-windows-x64.exe"
            -o "C:\cygwin64\bin\compress.exe"
      - name: CI test
        run: C:\cygwin64\bin\bash.exe -l "%cd%\scripts\ci_test.sh"
        env:
          CYGWIN_NOWINPATH: 1
          SHELLOPTS: igncr
