name: test

on:
  - push

jobs:
  ubuntu:
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
          - 3.1
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup dependencies
        run: sudo apt-get install -y libgmp-dev libtommath-dev ncompress
      - name: CI test
        run: scripts/ci_test.sh
        env:
          CI: True

  macos:
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7
          - 3.0
          - 3.1
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup dependencies
        run: |
          brew install gmp libtommath ncompress
          ln -s /usr/local/opt/ncompress/bin/compress /usr/local/bin/compress
      - name: CI test
        run: scripts/ci_test.sh
        env:
          CI: True

  windows-mingw:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 "{0}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            git
            make
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-curl
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gmp
            mingw-w64-x86_64-libtommath
            mingw-w64-x86_64-ruby
      - name: Setup dependencies
        run: >-
            curl -L "https://github.com/vapier/ncompress/releases/download/v5.0/compress-windows-x64.exe"
            -o "/usr/bin/compress.exe"
      - name: CI test
        run: scripts/ci_test.sh
        env:
          CI: True
          MSYSTEM: MINGW64
